[workspace]
members = [
	"projects/camkes-bindgen",
	"projects/hello-rust",
	"projects/client-server/components/client",
	"projects/client-server/components/server",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
