[package]
name = "camkes-bindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
anyhow = "1.0.68"
bindgen = "0.63.0"
glob = "0.3.1"
itertools = "0.10.5"
